services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${HTTP_PORT:-8000}:80"
    volumes:
      - ${APP_DIR:-./}:/srv/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./docker/php
      args:
        - PUID=${PUID:-1000}
        - PGID=${PGID:-1000}
        - LOCALE=${LOCALE:-POSIX}
        - PHP_VERSION=${PHP_VERSION:-8.3}
    volumes:
      - ${APP_DIR:-./}:/srv/app
      - ${HOME}/.git:/home/docksy/.git
    environment:
      - XDEBUG_CONFIG=client_host=${XDEBUG_CLIENT_HOST:-host.docker.internal} client_port=${XDEBUG_CLIENT_PORT:-9003}
      - XDEBUG_MODE=debug
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD:-my_password}@mysql:3306/${MYSQL_DATABASE:-my_app}?serverVersion=8&charset=utf8

  mysql:
    image: mysql:8
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-my_password}

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-my_password}
    ports:
      - "${PHPMYADMIN_PORT:-8800}:80"