version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ${APP_DIR}:/srv/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./docker/php
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - LOCALE=${LOCALE}
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${APP_DIR}:/srv/app
      - ${HOME}/.git:/home/docksy/.git
    environment:
      - XDEBUG_CONFIG=client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT}
      - XDEBUG_MODE=debug
      # This is extremely insecure and should be changed in production. But we need a privileged user here to be able to
      # create a second database for testing purposes with `bin/console doctrine:database:create -e test`.
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=8&charset=utf8

  mysql:
    image: mysql:8
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"